services:
    nginx:
        container_name: evtest-nginx
        image: nginx:1.27-alpine
        ports:
            - 80:80
        restart: on-failure
        volumes:
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html
        networks:
            - backend
        depends_on:
            - app

    app:
        container_name: evtest-app
        build:
            context: .docker/app
        restart: on-failure
        volumes:
            - ./:/var/www/html
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
      container_name: ${DB_HOST}
      image: mysql:8.4
      environment:
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
      restart: on-failure
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - ${DB_PORT}:${DB_PORT}
      networks:
        - backend

volumes:
  mysql:
    driver: local
networks:
    backend:
